version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: employee_management
    ports:
      - '5432:5432'
  server:
    image: docker-node
    build: .
    command: npm start
    depends_on:
      - db
    ports:
      - '3333:3333'
