version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: employee_management
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  web:
    image: larissapissurno/dockernode
    build: .
    command: npm start
    depends_on:
      - db
    ports:
      - '3333:3333'
    volumes:
      - .:/usr/app
